spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_journal
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
