spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_journal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

app:
  jwt:
    secret: "longrandomstringblablablaaiistakingoverblablablablablablablablablabla"
    expiration-minutes: 120